ROOT := $(shell while [ ! -e dune-project ] && [ "$$PWD" != "/" ]; do cd ..; done; pwd)
include $(ROOT)/etc/common.mk

TARGETS=$(filter-out %.1.lv,$(wildcard *.v) $(wildcard *.lv))

# This Makefile provides common build rules
# for dircotries which contain many separate
# small Koika modules

.PHONY: build
build: dune.inc
	@$(call emph-print,== <{ build($(SUBDIR)) }> ==)
	dune build @vo_files

build-%: % dune.inc FORCE
	@$(call emph2-print,== <{ build($(SUBDIR)/$*) }> ==)
	dune build $*o

.PHONY: cuttlec
cuttlec: dune.inc
	@$(call emph-print,== <{ cuttlec($(SUBDIR)) }> ==)
	dune build @compile

cuttlec-%: dune.inc FORCE
	@$(call emph2-print,== <{ cuttlec($(SUBDIR)/$*) }> ==)
	dune build @$*.d/compile

setup-sim-%: cuttlec-% FORCE
	$(eval BUILD_SUBDIR := $(patsubst $(ROOT)%,$(BUILD_DIR)%/$*.d,$(shell pwd)))
	$(verbose)# copy all files of the $*.etc folder into the $*.d folder generated by dune
	$(verbose)if [ -d $*.etc ]; then cp -rf "$*.etc/." "$(BUILD_SUBDIR)"; fi

compile-sim-%: setup-sim-% FORCE
	$(eval BUILD_SUBDIR := $(patsubst $(ROOT)%,$(BUILD_DIR)%/$*.d,$(shell pwd)))
	@$(call emph2-print,== <{ make($(SUBDIR)/$*) }> ==)
	$(MAKE) -C "$(BUILD_SUBDIR)"

.PHONY: compile-sim
compile-sim: $(foreach target,$(TARGETS),$(patsubst %,compile-sim-%,$(target)))



.PHONY: clean
clean:
	@$(call emph-print,== <{ clean($(SUBDIR)) }> ==)
	rm -f dune.inc
	rm -rf $(patsubst $(ROOT)%,$(BUILD_DIR)%,$(shell pwd))

dune.inc: *.v
	$(verbose)bash $(ROOT)/etc/configure.sh $$(pwd)

.PHONY: configure
configure:
	$(verbose)bash $(ROOT)/etc/configure.sh $$(pwd)

.PHONY: all
all: build cuttlec compile-sim




.PHONY: help
help::
	@echo ""
	@echo "all           - ∀ modules, build + compile + compile-sim"
	@echo "build         - ∀ modules, build (i.e. only evaluate rocq)"
	@echo "cuttlec       - ∀ modules, compile (i.e. invoke cuttlec)"
	@echo "compile-sim   - ∀ modules, compile cpp simulator (i.e. invoke make/gcc)"
	@echo
	@echo "∀ x : (*.v + *.lv),"
	@echo "build-x       - only build module x"
	@echo "cuttlec-x     - only compile module x"
	@echo "compile-sim-x - only compile cpp module x"
	@echo
	@echo "configure     - create dune.inc"
	@echo "clean         - clean build files"